version: "3.5"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    # network_mode: "host"
    volumes:
      - adguard_conf:/opt/adguard/conf
      - adguard_work:/opt/adguard/work
    restart: "unless-stopped"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 9880:80/tcp 
      - 443:443/tcp 
      - 443:443/udp 
      - 3001:3000/tcp
      - 853:853/tcp
      - 784:784/udp 
      - 853:853/udp 
      - 8853:8853/udp
      - 5443:5443/tcp 
      - 5443:5443/udp
volumes:
  adguard_conf:
  adguard_work:
